build:
  tests:
    before:

      - echo "USE mysql;\nCREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';\n" | mysql -u root
      - echo "GRANT ALL PRIVILEGES ON * . * TO 'homestead'@'localhost';\n" | mysql -u root
      - bash initial.sh
    override:
      -
        command: 'php vendor/codeception/codeception/codecept run functional --coverage-xml'
        coverage:
          file: 'tests/_output/coverage.xml'
          format: 'clover'
  environment:
    php: 7.0
    mysql: 5.6
checks:
  php: true
filter:
  excluded_paths:
    - tests/