build:
  dependencies:
    override:
      - composer install --no-interaction --no-scripts

  project_setup:
    before:
      - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
      - sudo service mysql start
      - mysql -h localhost --user=homestead --password=secret -e "CREATE DATABASE IF NOT EXISTS homestead CHARACTER SET utf8 COLLATE utf8_general_ci;"
      - mysql -h localhost --user=homestead --password=secret homestead < tests/_data/dump.sql

    override:
      - cp app/config/parameters.gitlab-ci.yml app/config/parameters.yml
      - composer install

      - echo "Install DB and seeders for it"
      - bash app/db-update.sh

      - echo "Setup Symfony CMF"
      - bash app/setup.sh

  tests:
    before:
      - echo "Generate build_bootstrap for testing"
      - php vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php

    override:
      -
        command: 'vendor/codeception/codeception/codecept run functional --coverage-xml'
        coverage:
          file: 'tests/_output/coverage.xml'
          format: 'clover'

  environment:
    php: 7.0
    mysql: 5.6
    apache2:
            modules: ['rewrite']
            sites:
                symfony_app:
                    web_root: 'web/'
                    host: 'local.dev'
                    rules:
                        - 'RewriteCond %{HTTP_REFERER} !^$'
                        - 'RewriteCond %{HTTP_REFERER} !^http://(www.)?example.com/ [NC]'
                        - 'RewriteRule .(gif|jpg|png)$ - [F]'
checks:
  php: true
filter:
  excluded_paths:
    - tests/