assetic:
    debug:          false # %kernel.debug%
    use_controller: false
    read_from:      %kernel.root_dir%/../web
    write_to:       %kernel.root_dir%/../web
    bundles:        [] # disable bundles parsing

    assets:
        sonata_admin_js:
            inputs:
                - bundles/sonatacore/vendor/jquery/dist/jquery.min.js
                - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
                - bundles/sonatacore/vendor/moment/min/moment.min.js
                - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
                - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
                - bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js
                - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
                - bundles/sonataadmin/vendor/jquery-form/jquery.form.js
                - bundles/sonataadmin/jquery/jquery.confirmExit.js
                - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
                - bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js
                - bundles/sonataadmin/vendor/iCheck/icheck.min.js
                - bundles/sonataadmin/vendor/slimScroll/jquery.slimscroll.min.js
                - bundles/sonataadmin/vendor/waypoints/lib/jquery.waypoints.min.js
                - bundles/sonataadmin/vendor/waypoints/lib/shortcuts/sticky.min.js
                - bundles/sonataadmin/vendor/readmore-js/readmore.min.js
                - bundles/sonataadmin/Admin.js
                - bundles/sonataadmin/treeview.js
                - bundles/sonatapage/sonata-page.back.min.js

        sonata_admin_css:
            inputs:
                - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
                - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
                - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
                - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
                - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css
                - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
                - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
                - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
                - bundles/sonataadmin/css/styles.css
                - bundles/sonataadmin/css/layout.css
                - bundles/sonataadmin/css/tree.css
                - bundles/sonataadmin/vendor/jqueryui/themes/flick/jquery-ui.min.css
                - bundles/sonatapage/sonata-page.back.min.css
                - styles/style.css

        sonata_formatter_js:
            inputs:
                - bundles/sonataformatter/vendor/ckeditor/ckeditor.js
                - bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
                - bundles/sonataformatter/markitup/sets/markdown/set.js
                - bundles/sonataformatter/markitup/sets/html/set.js
                - bundles/sonataformatter/markitup/sets/textile/set.js

        font-awesome-otf:
            inputs: 'bundles/sonatacore/vendor/components-font-awesome/fonts/FontAwesome.otf'
            output: 'fonts/FontAwesome.otf'

        font-awesome-eot:
            inputs: 'bundles/sonatacore/vendor/components-font-awesome/fonts/fontawesome-webfont.eot'
            output: 'fonts/fontawesome-webfont.eot'

        font-awesome-svg:
            inputs: 'bundles/sonatacore/vendor/components-font-awesome/fonts/fontawesome-webfont.svg'
            output: 'fonts/fontawesome-webfont.svg'

        font-awesome-ttf:
            inputs: 'bundles/sonatacore/vendor/components-font-awesome/fonts/fontawesome-webfont.ttf'
            output: 'fonts/fontawesome-webfont.ttf'

        font-awesome-woff:
            inputs: 'bundles/sonatacore/vendor/components-font-awesome/fonts/fontawesome-webfont.woff'
            output: 'fonts/fontawesome-webfont.woff'
