app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   /

# FOSUserBundle's routing
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /profile

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /profile

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /login

# Admin's routing
sonata_user:
  resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
  prefix: /admin

# Media routes
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

# SonataPageBundle routes
sonata_page_exceptions:
    resource: '@SonataPageBundle/Resources/config/routing/exceptions.xml'
    prefix: /

#SonataNewsBundle
news:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /news


# SonataCacheBundle route
sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

# Routers for rest api
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

sonata_api_media:
    type:         rest
    prefix:       /api
    resource:     "@SonataMediaBundle/Resources/config/routing/api.xml"

sonata_api_user:
    type:         rest
    prefix:       /api/user
    resource:     "@SonataUserBundle/Resources/config/routing/api.xml"

sonata_api_news:
    type:         rest
    prefix:       /api
    resource:     "@SonataNewsBundle/Resources/config/routing/api.xml"

sonata_api_page:
    type:         rest
    prefix:       /api/page
    resource:     "@SonataPageBundle/Resources/config/routing/api.xml"

sonata_api_messages:
    type:         rest
    prefix:       /api
    resource:     "@MessageBundle/Resources/config/routing/api.xml"

admin:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /admin

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin
