# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, SONATA]
        SONATA:
          - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # comment it when using acl
          - ROLE_SONATA_PAGE_ADMIN_BLOCK_EDIT

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        admin:
            pattern:  /admin(.*)
            context:  user
            form_login:
                provider:  fos_userbundle
                login_path:  /admin/login
                use_forward:  false
                check_path:  /admin/login_check
                failure_path:  null
            logout:
                path:  /admin/logout
            anonymous:  true
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                login_path:        /login
                failure_path:      /login

                oauth_user_provider:
                    service: fos_user_provider
            logout:
                handlers: ['sonata.page.cms_manager_selector']
            anonymous:  true

        login:
            pattern:  ^/login$
            security: false

            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
      # URL of FOSUserBundle which need to be available to anonymous users
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

      # Admin login page needs to be access without credential
      - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

      # Secured part of the site
      # This config requires being logged for the whole site
      # and having the admin role for the admin part.
      # Change these rules to adapt them to your needs
      - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
      - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
