# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    nix_mailer_service:
        class: UserBundle\Services\NixMailerService
        arguments:
                - '@mailer'
                - '@router'
                - '@templating'
                -
                    confirmation.template: '%fos_user.registration.confirmation.template%'
                    resetting.template: '%fos_user.resetting.email.template%'
                    from_email:
                        confirmation: '%fos_user.registration.confirmation.from_email%'
                        resetting: '%fos_user.resetting.email.from_email%'
                    header_project: '%nix_header_project%'
                    header_emails: '%nix_header_emails%'
                    header_external: '%nix_header_external%'