sonata_user:
    #security_acl: true # Uncomment for ACL support
    manager_type: orm  # can be orm or mongodb
    admin:                  # Admin Classes
        user:
          class:          Application\Sonata\UserBundle\Admin\UserAdmin
          #Sonata\UserBundle\Admin\Entity\UserAdmin
          translation:    SonataUserBundle
    profile:
        form:
          validation_groups:  [Profile, Default]
