sonata_news:
    title:        "%link%"
    link:         "%title%"
    description:  Cool bundles on top of Symfony2
    salt:         'secureToken'
    permalink_generator: sonata.news.permalink.date # sonata.news.permalink.collection

    comment:
        notification:
            emails:   [email@example.org, email2@example.org]
            from:     "%admin_address%"
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'
