sonata_user:
    #security_acl: true # Uncomment for ACL support
    manager_type: orm  # can be orm or mongodb
    admin:                  # Admin Classes
        user:
          class:          Application\Sonata\UserBundle\Admin\UserAdmin
          #Sonata\UserBundle\Admin\Entity\UserAdmin
          translation:    SonataUserBundle
    profile:
            register:
                # You may customize the registration forms over here
                form:
                    type:                 sonata_user_registration
                    handler:              sonata.user.registration.form.handler.default
                    name:                 sonata_user_registration_form
                    validation_groups:
                        # Defaults:
                        - Registration
                        - Default
                # This allows you to specify where you want your user redirected once he activated his account
                confirm:
                    redirect:
                        # Set it to false to disable redirection
                        route: 'sonata_user_profile_show'
                        route_parameters: ~

            # Profile Form (firstname, lastname, etc ...)
            form:
                type:               sonata_user_profile
                handler:            sonata.user.profile.form.handler.default
                name:               sonata_user_profile_form
                validation_groups:  [Profile]
