services:
    message.manager.message:
        class: MessageBundle\Entity\MessageTemplateManager
        arguments:
              - MessageBundle\Entity\MessageTemplate
              - '@doctrine'

    message.controller.api.message:
        class: MessageBundle\Controller\Api\MessageTemplateController
        arguments:
              - '@message.manager.message'
              - '@form.factory'

    message.serializer.handler.message:
        class: MessageBundle\Serializer\MessageSerializerHandler
        tags:
              - { name: jms_serializer.subscribing_handler }
        arguments:
            - '@message.manager.message'

    sonata.page.api.form.type.message:
        class: MessageBundle\Form\Type\ApiMessageType
        tags:
              - { name: form.type, alias: message_api_form_message}
        arguments:
            - '@jms_serializer.metadata_factory'
            - '@doctrine'
            - message_api_form_message
            - MessageBundle\Entity\MessageTemplate
            - sonata_api_write

    message.manager.sentmessage:
        class: MessageBundle\Entity\MessageUserManager
        arguments:
            - MessageBundle\Entity\MessageUser
            - '@doctrine'

    message.controller.api.sentmessage:
        class: MessageBundle\Controller\Api\MessageUserController
        arguments:
            - '@message.manager.sentmessage'
            - '@message.manager.message'
            - '@sonata.user.user_manager'
            - '@form.factory'
